wip
Signed-off-by: Pieter Viljoen <ptr727@users.noreply.github.com>

diff --git a/.github/workflows/test-pull-request.yml b/.github/workflows/test-pull-request.yml
--- a/.github/workflows/test-pull-request.yml
+++ b/.github/workflows/test-pull-request.yml
@@ -20,3 +20,26 @@ jobs:
     name: Test docker build
     uses: ./.github/workflows/test-docker-task.yml
     secrets: inherit
+
+  # TODO: Workaround for GitHub Actions not supporting status checks on conditional jobs
+  # https://github.com/orgs/community/discussions/12395#discussioncomment-12970019
+  check-workflow-status:
+    name: Check workflow status job
+    runs-on: ubuntu-latest
+    needs:
+      [
+        test-build,
+        test-docker,
+      ]
+    if: always()
+    steps:
+      - name: Check workflow status step
+        run: |
+          exit_on_result() {
+            if [[ "$2" == "failure" || "$2" == "cancelled" ]]; then
+              echo "Job '$1' failed or was cancelled."
+              exit 1
+            fi
+          }
+          exit_on_result "test-build" "${{ needs.test-build.result }}"
+          exit_on_result "test-docker" "${{ needs.test-docker.result }}"
